### ISSUE TITLE
can you print the cutoff value?

### ISSUE THREAD

**Issue by liamxg** [PoonLab/clustuneR#15]
<img width="789" alt="image" src="https://github.com/PoonLab/clustuneR/assets/46078579/93302b42-899c-4ac8-a94c-9b4f7b6efc3c">

**Comment by ArtPoon** [comment]
Hi @liamxg, you should be able to retrieve the minimum value from the data objects used in the R script.  Which script are you using, specifically?

**Comment by ArtPoon** [comment]
Okay, it looks like you've just copied the example in the `README` document, so I'll assume you are running the following code:
```R
cutoffs <- sapply(param.list, function(x) x$branch.thresh)
par(mar=c(5,5,1,1))
plot(cutoffs, delta.AIC, type='l', col='cadetblue', lwd=2)
abline(h=0, lty=2)
```

In which case, you should be able to retrieve and display the minimum as follows:
```R
cutoffs <- sapply(param.list, function(x) x$branch.thresh)
min.cutoff <- cutoffs[which.min(delta.AIC)]
par(mar=c(5,5,1,1))
plot(cutoffs, delta.AIC, type='l', col='cadetblue', lwd=2)
abline(h=0, lty=2)
text(x=min.cutoff, y=min(delta.AIC), label=min.cutoff, cex=0.8, adj=0)
```
