### ISSUE TITLE
Problem with lazyloading

### ISSUE THREAD

**Issue by smarini** [PoonLab/clustuneR#7]
Hi and thank you for making clustuneR!

I am try to install it for my own research, but I get the following error

```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 11 elements
ERROR: lazydata failed for package ‘clustuneR’
```
I am using the install_github function

**Comment by ArtPoon** [comment]
Hi @smarini - thanks for your feedback!  Can you please provide us with information about your operating system and version of R?

**Comment by ArtPoon** [comment]
@ConnorChato - I reproduced this issue on macOS Catalina 10.15.7 and R version 4.0.2, and on Ubuntu 18.04.5 with R 3.6.3:
```console
art@Wernstrom clustuneR % R CMD INSTALL .
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
* installing *source* package ‘clustuneR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 11 elements
ERROR: lazydata failed for package ‘clustuneR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/clustuneR’
```

**Comment by ArtPoon** [comment]
Ah, it's the `txt` files in the `/data` folder causing this problem:
```console
art@Wernstrom clustuneR % cd data
art@Wernstrom data % ls
IQTREE_log_ex.txt	cluster.ex.RData	graph.ex.RData
RAxML_log_ex.txt	extended.tree.ex.RData	old.tree.ex.RData
alignment.ex.RData	full.tree.ex.RData	seq.info.ex.RData
art@Wernstrom data % rm IQTREE_log_ex.txt 
art@Wernstrom data % rm RAxML_log_ex.txt 
art@Wernstrom clustuneR % R CMD INSTALL .
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
* installing *source* package ‘clustuneR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (clustuneR)
```

**Comment by ArtPoon** [comment]
@smarini  - can you please try again?

**Comment by ConnorChato** [comment]
Thanks for catching that installation issu! Those txt files were example log files which I was using to test some parsing functions. Still nice to have as examples though - maybe I'll try to find a new spot to put them.

**Comment by ArtPoon** [comment]
> Thanks for catching that installation issu! Those txt files were example log files which I was using to test some parsing functions. Still nice to have as examples though - maybe I'll try to find a new spot to put them.

@ConnorChato - The `txt` files should go into `inst/extdata`.
https://r-pkgs.org/data.html#data-extdata
